### PR TITLE
Patch 190

### PR DESCRIPTION
**Pull request by sparksofinsanity**
some small corrections to the german and spanish translation

### CODE REVIEW

**Comment by the-j0k3r** [comment]
@sparksofinsanity can this be merged?

**Comment by sparksofinsanity** [comment]
@the-j0k3r

what can be merged?
I have already applied your patch and since it concerns a different file, there should be no problems.

**Comment by the-j0k3r** [comment]
No I mean this pr patch of your merged into dd-wrt, you wanna merge the work so far or wait?

**Comment by sparksofinsanity** [comment]
It can all be merged into master

**Comment by the-j0k3r** [comment]
@sparksofinsanity its been merged https://svn.dd-wrt.com/changeset/49001

both this and my other PR, so Im closing this.

**Pull request closed without merging**
