### PR TITLE
upstream dd-wrt updates

### PR DESCRIPTION
**Pull request by the-j0k3r**
@BrainSlayer 

As promised, is this good for you to grab?

### CODE REVIEW

**Comment by the-j0k3r** [comment]
>  because core.css is called as new http request and has a different error code then

sorry, if the correct css is core.css youre saying it wont work? so the the solution must be to include the error code in `themename.stylus` and then import the rest right?

thats not a terrible compromise, its very little css to leave behind.

**Comment by BrainSlayer** [comment]
listen. the stylus file is directly referenced from the http request to the error page. but the core.css file is loaded with a separate request and this separate request does not know about any error code. its even a independend thread. so i moved the error code style from core.css to aeon.stylus

**Comment by the-j0k3r** [comment]
> listen. the stylus file is directly referenced from the http request to the error page. but the core.css file is loaded with a separate request and this separate request does not know about any error code. its even a independend thread. so i moved the error code style from core.css to aeon.stylus

Sure thats what I thought after you said it.

re: other themes, Once you confirm/verify all the CSS is the same across themes, the remainder can be just like aeon, and I will be curious how many bytes less after compression this will gain.

re: these commits, on this PR, you are pulling all of them in right? if so let me know when youre done so I can close this and kill the branch so I can do other work on another PR for the old themes.

**Comment by BrainSlayer** [comment]
i'm already done

**Comment by the-j0k3r** [comment]
> i'm already done

I dont see https://github.com/mirror/dd-wrt/pull/44/commits/a914ed60b36091439647eed543bf66413a7ee7f6 maybe something else maybe missng havnt checked.

**Comment by the-j0k3r** [comment]
Also dont see https://github.com/mirror/dd-wrt/pull/44/commits/40037fb36dc08152cbc73e82a01d27e9e4884811

**Comment by the-j0k3r** [comment]
blind as a bat today, sorry =)

**Comment by BrainSlayer** [comment]
we have now a new include include does not work for embedded style sheets. so it wont load core.css. i will fix this in another way

**Comment by the-j0k3r** [comment]
> we have now a new problem. include does not work for embedded style sheets. so it wont load core.css. i will fix this in another way

Why does it work with old styles then? Must be the somewhere the roundabout the way the new styles were implemented.

In any case, let me see what hack you find.

**Comment by BrainSlayer** [comment]
the old styles did not embedd the css into html code. it was a css file referenced as link `<link type="text/css" rel="stylesheet" href="style/elegant/style.css" />` for instance

**Comment by BrainSlayer** [comment]
i have written now a solution and converted all files to use core.css to reduce maintainance effort

**Comment by the-j0k3r** [comment]
> i have written now a solution and converted all files to use core.css to reduce maintainance effort

The problem with that is the core.css file doesn't in https://github.com/mirror/dd-wrt/tree/master/src/router/kromo/dd-wrt/ddwrt_inspired_themes and I dont see any imports

**Comment by the-j0k3r** [comment]
ping above @BrainSlayer

**Comment by BrainSlayer** [comment]
now its there

**Comment by the-j0k3r** [comment]
> now its there

and the @imports will this new way suport the eeor redesign also or does that css be like in main file?

**Comment by BrainSlayer** [comment]
the imports are not required anymore. its handled by cgi code. and yes it does handle the error redesign

**Comment by the-j0k3r** [comment]
> the imports are not required anymore. its handled by cgi code. and yes it does handle the error redesign

Great stuff. thanks for that. Less work is always better. Out of curiosity how many bytes do we save this way in comparison, you said 11~15kb per before and now?

Re: old themes rework has started with CSS cleanup/reformat to begin and then Ill need to add a directory where I can put common code to be imported in to those, like error code with the absolute minimum required `:root` CSS vars for that to work.
Later when the error redesign works for those as well via DD-WRT, I plan on adding full root values for them.

One thing Im unsure about, is how the old styles work when you toggle dark styles, wheres that CSS for that?

Mainly because, with dark styles, the hotspot logos, even though they are updated, at least the wifidog is pretty much unreadable text portion, so  Ill add the redesigned one somewhere so when dark toggle is on it uses that somehow. (Have to dig into source).

But yep, the train has left the station.

Also do you want to keep this directory and contents for some historic/hysteric reason or can I get rid of it? https://github.com/mirror/dd-wrt/tree/master/src/router/kromo/old_not_maintained

**Comment by BrainSlayer** [comment]
we do not save much bytes. the compression algorithm of the filesystem which is used does store only unique byte sequences. so doubled entries are optimized out. for the dark style.if dark mode is enabled elegant/fresh-dark.css is attached. thats all.
this applies only for elegant, blue, green, orange, red, cyan, yellow styles. 

old_not_maintained is just backup crap. you dont need to care about my trashbin.

**Pull request closed without merging**
