### PR TITLE
WireGuard clean up and fixes

### PR DESCRIPTION
**Pull request by egc112**
During testing I found a bug, the watchdog script restarts the tunnel but  when the tunnel restarts there is a thorough clean up also from running watchdog scripts.
Depending on how fast etc the watchdog script kills itself before it is finished.
So I had to spawn the restart process.
Also did some extensive  cleaning and fixing other minor issues 😊

### CODE REVIEW

**Comment by the-j0k3r** [comment]
@brainsalyer shameless ping =)

/me runs

**Comment by egc112** [comment]
Thanks!

**Comment by egc112** [comment]
Well just have to be patient

**Comment by the-j0k3r** [comment]
It maybe time for me to try out wireguard =)

congrats and thanks are in order =)

**Comment by egc112** [comment]
Thanks!

**Pull request closed without merging**
