### PR TITLE
hc-changepass

### PR DESCRIPTION
**Pull request by the-j0k3r**

### CODE REVIEW

**Comment by kernel-panic69** [comment]
This should be changed so it follows the wiki, perhaps.  Broadcom is Client Bridge and there are two separate wikis for this mode because the procedure has notable differences.  Just my thoughts.

wl_basic.clientRelayd="Client Bridged";

**Comment by the-j0k3r** [comment]
This use to be and has always been until now

`wl_basic.clientRelayd="Client Bridge (Routed)";`

it was changed to follow the logic implied

`wl_basic.clientRelayd="Routed Client Bridge";`

The Wiki is the wiki... I can revert to old but never to just the suggested since it doesn't Imply `Routed`

**Comment by kernel-panic69** [comment]
Client Bridge is Broadcom.  Client Bridge (routed) is all others that support the functionality.  I have no control over who created wiki pages, and I cannot delete pages in the wiki to match code changes.  It is what it is.

**Comment by the-j0k3r** [comment]
Makes no sense to me to show that string if the router doesn't support that functionality, end of story, Wiki wise, idk I bet it was writen before the last ice age.

Ive reverted it to what it use to be and until someone provides a proper fix with related strings only displayed on routers that support it, it will remain.

**Comment by the-j0k3r** [comment]
>The difference between client bridge and client bridge routed is the way its faked

>On some devices both are offered routed and standard client bridge
>this is why there is the hind behind how its done

>then you have 2 client bridge entries on some devices

And that is the information I have from BS.

**Comment by kernel-panic69** [comment]
Thanks, I already knew all of that about the bridge modes.  I was also aware of the rest of that.  Enjoy your Sunday.

**Comment by the-j0k3r** [comment]
https://svn.dd-wrt.com/changeset/49155 wiki now fully obsolete where these strings are concerned. BS decided these are actually correct after our discussion about your report here.

**Pull request closed without merging**
