### PR TITLE
nvram help

### PR DESCRIPTION
**Pull request by blkthorne**

### CODE REVIEW

**Comment by the-j0k3r** [comment]
> | means "or" in computer science and is much more common in syntax description than using it as a written word. please rework

`||` = or
`|` != or

**Comment by blkthorne** [comment]
| is more common in Usage section of a command help, comma for Options section but especially short or long form. There is no standard, only opinions and we can all find examples to suit our preferences. I chose human readability, but also because there is some space available, to each their own. This is a command help after all so it's for those who do not know what they are doing. Maybe there is a compromise, to keep | tradition in Usage, but also "or" below in the descriptions for new or uninformed users.

**Comment by BrainSlayer** [comment]
|| is boolean or in C code. a single | is just or

Am 20.09.2022 um 16:32 schrieb the-j0k3r:

**Comment by BrainSlayer** [comment]
merged

**Comment by the-j0k3r** [comment]
> but also "or" below in the descriptions for new or uninformed users.

TBH people need to learn, it great to excuse/rework whatever for novices hence this was added in first place, The point is can never have anything foolproof and anyone that tries to will always fail.

But I agree, there is no standard and each developer does whatever they are used to. Anyway, my point was/is there is no consistency amongst any projects to have a widely accepted anything or anything like a documentation standard.

I bet none will read it anyway, this is a fact most users especially novices dont read anything, less than 1% does.

**Comment by kernel-panic69** [comment]
The current iteration was pretty much what was going to be submitted.  Thank you for stepping up, @blkthorne, and thanks for considering this, @BrainSlayer.

> and Ill leave with a thanks to you for submitting the patch, only way things will ever get done in any project.

Not entirely true.  I'd address the elephant in the room, but it's not worth it.  Folks are happy that you're doing what you do, and that's all that matters.

**Comment by the-j0k3r** [comment]
The old rhetoric ala KP strikes again as usual, get a hint, no one is interested in your dramas and imaginary elephants.

**Comment by blkthorne** [comment]
> Maybe there is a compromise, to keep | tradition in Usage, but also "or" below in the descriptions for new or uninformed users.

> TBH people need to learn, it great to excuse/rework whatever for novices hence this was added in first place, The point is can never have anything foolproof and anyone that tries to will always fail.

A missed opportunity to hint users meaning. Capitalized OR would also have been rejected, but it would have been clear to all.
The compromise above would have been rejected too for the same reasons, but there is an alternative, to keep usage brackets.

What I mean by this is same as the initial pull request or first commit, [show] [getall] [clear] [erase] arguments are independent.
This clearly suggests the arguments should be issued separately and then descriptions below with | reveal the shared functions.

**Comment by BrainSlayer** [comment]
please behave

Am 22.09.2022 um 12:30 schrieb the-j0k3r:

**Pull request closed without merging**
