### PR TITLE
Kromo and helps trings

### PR DESCRIPTION
**Pull request by the-j0k3r**

### CODE REVIEW

**Comment by sparksofinsanity** [comment]
looks like you broke english and german again 

the whole "log" strings have moved down again

**Comment by the-j0k3r** [comment]
No problem, the position is intentional, this lot is all entries (mainly) for the Firewall.asp so help strings are just after the variable definitions.

Looks OK here atm, I did ask BS for a r7800 build, cant see one yet, but all looks wonderful.

**Comment by sparksofinsanity** [comment]
Well, that's what I thought.
But if you make a full syncronisation.

Then the english file is still the reference. 
And then you should also adjust the positions.

I try to do a full syncronization between english and german.
If you compare the files in a diff viewer you will see that the files up to line 825 are pretty much identical.

But it is a lot of work.
And I will probably still need 2 weeks for it.

**Comment by the-j0k3r** [comment]
> By this I mean automated via script.

Sure easier said than done, I have scripts already, but none to do this. Mainly cause regex is not my forte, i'de spend more time getting the regex right than doing it by hand likely..

But I like the way you're thinking.

Thanks for your help anyway.

**Pull request closed without merging**
