### PR TITLE
more fixes and clenup

### PR DESCRIPTION
**Pull request by the-j0k3r**
@BrainSlayer here are some more goodies to help squash some visual nasties still not being addressed.

Ok let me start with the issues

1) Help/about pages aren't loading fresh-dark.css when the `if("<% nvg("router_style_dark"); %>"=="1")` is set, Looked around but couldn't see where this is at. its looked menacing, so I decided not to try and do this myself.
Either fresh dark is loaded or (I prefer to) we can separate the about/help css dark fixes into separate file and load that? Would that be better? 

2) you have a dead link in common.js

https://github.com/mirror/dd-wrt/blob/44bde1841562a0a0ab2bea0ae2473ce19c3a992e/src/router/kromo/dd-wrt/common.js#L755

http://www.dd-wrt.com/help/english/ goes nowhere these days it intends to, maybe it did in the past, I was looking for the help pages related stuffs and I found that legacy nugget. Perhaps you meant to point that to the wiki? Wasn't sure so you decide.

3) Previous fix https://github.com/mirror/dd-wrt/pull/48/files#diff-c95a94ed9a4c3d643bc2b6ba9016905fdf1b063f75af7f3ba5c4d7555352095e to the sysctl breaks between fieldsets actually **add more breaks than needed after random nr of fieldsets ONLY**
     rest is fine has intended.  If you can, please have mercy fixing this without breaking all other pages would be nice.
Screenshot 2021-10-04 at 12-06-45 Nexus (build 47510) - Sysctl Configuration

## Good news

Most of the issues with classic dark styles blue/yellow red etc are done and gone just remains the help pages bit

What remains is maybe to make the blue/yellow/red/orange/cyan/elegant light styles have not so white backgrounds, maybe `#eeeeee` or `#cccccc` and other minor tweaks to freshen them up a bit. this is fast work.

Then you have to decide what will happen to  Brainslayer/kromo/vikar/xirian, I haven't touched those but they need love I guess, I haven't really looked beyond the nasty effect some of them have on my sensitive retinas, lets just say that =) wink wink nudge nudge.

### CODE REVIEW

**Comment by the-j0k3r** [comment]
ping the man @BrainSlayer  you have to come down for a visit

**Comment by BrainSlayer** [comment]
baaa. most of the fixes are just whitespace changes. this is totally unneccessary. the code is formated by a automatic script. totally pointless

**Comment by BrainSlayer** [comment]
your line break issue with sysctl was simple. you did not take care about the required bracelets. so it wasnt part of the if statement

**Comment by the-j0k3r** [comment]
> baaa. most of the fixes are just whitespace changes. this is totally unneccessary. the code is formated by a automatic script. totally pointless

they are separate commits as you previously asked, my editor auto kills these when detected, so your script is not doing something it should.

and since they are separate commits you dont have to pull those in, if you prefer the code to have trailing whitespaces everywhere.

Can we address the issues though please?

**Comment by the-j0k3r** [comment]
> your line break issue with sysctl was simple. you did not take care about the required bracelets. so it wasnt part of the if statement

thanks, I did ask for you to look at it I wasn't sure if that's all it took, clearly.

**Comment by BrainSlayer** [comment]
nope. without brackets the next single statement is considered. it is unrelated to lines.
so if (1)
           dosomething(); dosometing_2();
       
       
will only consider dosomething, but no the second call

**Comment by the-j0k3r** [comment]
.@brainslayer, still need to update some css for the inspired themes  to address the improvements in colors for syslog and status colors so for next build there aren't broken things where they shouldn't.

Just was knackered and forgot.

What would you like me to do for the about/help dark fixes for classic themes while Im at this, is it simpler for you to inject a separate stylesheet or as is OK?

**Comment by BrainSlayer** [comment]
i can take any solution. best would it be if the main stylesheet is used for these pages. this is most simple for us all

**Comment by the-j0k3r** [comment]
> i can take any solution. best would it be if the main stylesheet is used for these pages. this is most simple for us all

Depends what you mean by main stylesheet, if that means fresh-dark then thats it.

How it is currently is that help.css is being pulled into the about page, why idk since it has separate stylesheet which is now hardcoded in the cgi but still it pulls the help.css

this line https://github.com/mirror/dd-wrt/commit/e2d39dff6898ce2fe4eb95c76fba0a123c19eb7d#diff-8870f876204c092cc6e85bc5f369236f758b471e0a46b615dcccab013781af96R2281 

So technically the help page.css could very well just carry the about page classes (it wouldn't work any differently) too

What I actually prefer is to have different stylesheets for different pages to keep things simpler.

But yea, makes no sense to me how this was done in the past, if you add inline stylesheet for the about page, then no need to force the browsers to load some other stylesheet for what is in essence unrelated page.

OK so, we have to decide on the about page contents at some stage. We talked about what belongs/not belongs there, and we agree, but how to proceed with adding related release features and distribution type for each individual router so only relevant info is displayed IDK.

**Comment by BrainSlayer** [comment]
fresh-dark is just one variant

**Comment by the-j0k3r** [comment]
> fresh-dark is just one variant

for classic themes when dark, there is no other that carries dark anything. unless you mean some other stylesheet or I dont understand what you mean.

**Pull request closed without merging**
