### PR TITLE
prevent kill pppd process which started from pppoe

### PR DESCRIPTION
**Pull request by tenwx**

### CODE REVIEW

**Comment by jkldgoefgkljefogeg** [comment]
This is an unofficial mirror of ddwrt svn repository.

**Comment by GXTX** [comment]
http://svn.dd-wrt.com/
@tenwx

**Comment by jkldgoefgkljefogeg** [comment]
@GXTX how do you actually contribute to the official repository? BrainSlayer is the only one with write access

**Comment by GXTX** [comment]
Brainslayer and Kong yes, but they do eventually read and follow through with tickets (that are serious). I really think they'd benefit with actually using GitHub or really any other git type platform.

**Pull request closed without merging**
