### PR TITLE
cleanup and additions

### PR DESCRIPTION
**Pull request by the-j0k3r**
@BrainSlayer 

1) can I import the error redesign via @import into the dd-wrt-inspired themes included, or does this have to be loaded via cgi?

I added https://github.com/the-j0k3r/dd-wrt/commit/1c25de96ff2961ff6b40ec10ca0131effca8b538

if so let me know so can do the import and remove the error css from core.css for dd-wrt inspired stuff and I can remove it from upstream as well to further easy maintenance.

2) the old styles I reformatted so its easier for me to read the things and fix em later

I imported the error CSS into the old styles? Does this need something else to work with all old classic styles or some other magic needs to be done for that to work?

this would be nice to do sometime, no rush, at least its there now, ready.

3) please  test https://github.com/the-j0k3r/dd-wrt/commit/071ac4b42dda99ade0fdf7fd26e32985dc223564

if that doesn't work as is,we have to look into.

I couldn't hack the image as a replacement to test, tried a few things and ran out of time, but the svg works fine in any browser. Technically this should just work. (famous last words)

dont forget white spaces changes hiding

for split diff use https://github.com/mirror/dd-wrt/pull/46/files?diff=split&w=1
for unified diff use https://github.com/mirror/dd-wrt/pull/46/files?diff=unified&w=1

### CODE REVIEW

**Comment by the-j0k3r** [comment]
@BrainSlayer  so things Im doing.

the dd-wrt logos included are all being redesigned to get rid of the feathering e.g the help ones on classic themes and so on.

trying to come up with a new favicon design to make it cleaner/

trying to improve the about page a little more, re: this, the micro builds dont have the new themes right?

once all these are done incluing the simpler core.css with error css imported then I can try work on other stuff.

**Comment by BrainSlayer** [comment]
okay. will wait for the final version

**Comment by BrainSlayer** [comment]
for your question. yes you can manually import it. the cgi code does nothing more than resolving the import as plain text since i cannot include external css in the error page. so all is generated as embedded html code out from these 2 plain css files. core.css is inserted first, followed by the style file.

**Comment by BrainSlayer** [comment]
when you are done. can you please squash some of these commits, to make review work easier before merging?

**Comment by the-j0k3r** [comment]
Will the error code work for classic themes?

>for your question. yes you can manually import it. the cgi code does nothing more than resolving the import as plain text since i cannot include external css in the error page

I will simplify the core.css by removing the error code and importing the error code via @import url, which is the point of keeping it in separate file to make updates easier and I can remove the error code from my project as its a huge bug atm.

But after your reply, Im unsure it will be OK.

Ill squash all the reformat + import error code commits as they are all like type commits.

**Comment by BrainSlayer** [comment]
for classic themes the error code redesign is ignored since its part of the themes. if we want to use it for the classic themes, we need again to split it up and make a error code only css which excludes restyling of everything else. shouldnt be that hard

**Comment by the-j0k3r** [comment]
@BrainSlayer can you check that https://github.com/the-j0k3r/dd-wrt/commit/7deb5caf1ad36e5e1fb888752893fe225046090e is OK somehow I think its not.

>for classic themes the error code redesign is ignored since its part of the themes. if we want to use it for the classic themes, we need again to split it up and make a error code only css which excludes restyling of everything else. shouldnt be that hard

The error CSS its now imported into all classic themes and error CSS is already separated into two files, one that has the root values and one that has all CSS rules.

The error CSS rules is imported into ALL classic + inspired themes while the root values is only imported into the classic themes. because all inspired themes already have root values so we dont want duplication wherever possible.

I think thhis is all squashed as far as I can. I can squash it all into one commit if you like too.

**Comment by the-j0k3r** [comment]
Ah yes, the progress commit https://github.com/the-j0k3r/dd-wrt/commit/f6fe1d37f8de92f11b13f54995b43b6cee9f229a this needs to be tested that it works when compiled. If it does then fine, if not, ouch.

**Comment by the-j0k3r** [comment]
@BrainSlayer when you have time/patience please review.

**Comment by BrainSlayer** [comment]
from first view it looks like i have to write cgi code to handle the error strings and codes in error_common.css etc. but as i said. the error codes must be embedded in the error html. otherwise this will not work. so take off the error css from the styles and place them as separate independend files. these will then just be used for the error pages only and excluded from all styles.

**Comment by BrainSlayer** [comment]
but i can do this on my own, if needed

**Comment by the-j0k3r** [comment]
>  but as i said. the error codes must be embedded in the error html. otherwise this will not work. so take off the error css from the styles and place them as separate independend files. these will then just be used for the error pages only and excluded from all styles.

done in https://github.com/mirror/dd-wrt/pull/46/commits/79ba3c6e7907ecf2bf1a3981b2ec12623bdfa557

there is only one `error_common.css` file in common_style directory

>from first view it looks like i have to write cgi code to handle the error strings and codes in error_common.css

This was the original idea to include the redesign by default in all themes.

This is all fine and dandy until someone with internet explorer 1.1 comes around. Do you really want to support IE explorers? If not then more stuff can be ripped out.

**Comment by the-j0k3r** [comment]
Also this stuff

https://github.com/mirror/dd-wrt/blob/74bd9e7f3e7251407d7899342f7fe6e10f279d3a/src/router/httpd/httpd.c#L508

the `BGCOLOR=\"#cc9999\"` could be replaced by something like `CLASS=\"error-bg-color\"` and then we can assign that color on the `error_common.css`

like e.g.

```css
.error-bg-color {
    background-color: some color
}
```

and then the `error_common.css` can be updated to reflect this. Since using inline HTML that defines colors is generally a thing best avoided imo.

But you dont have to do that, I can simply do the replacing myself when the code is re-written, it will give me a chance to get more familiar with C and your design implementations choices and the source code in general.

**Comment by BrainSlayer** [comment]
this works only if we do special css for each error code. the problem in the code injection. the handler for the file just know the current error code. but while refering the css file with import, the error code is just 200. the original error code is only known by the error handler which creates the error web page. this is why it needs to be embedded. so its pointless to create a unique id. its definitly more clean, but makes no difference. i follow your approach and will create a own id for it

**Comment by the-j0k3r** [comment]
>  so its pointless to create a unique id. its definitly more clean, but makes no difference. i follow your approach and will create a own id for it

What I outlined. youre not creating a unique anything, you simply replace the inline color with a class that can be styled in CSS. I dont see how that is unique. 

`BGCOLOR=\"#cc9999\"` becomes `CLASS=\"error-bg-color\"` which is then styled in the CSS, it would behave the same. Unless there's something weird going on.

**Comment by the-j0k3r** [comment]
let me know when you grabbed all this and if the progress svg works or not.

thanks

**Comment by the-j0k3r** [comment]
Ive added https://github.com/the-j0k3r/dd-wrt/pull/46/commits/8198b2091afbfb893b2246bd3593d144d36ba707 this is a preview on the browser, not compiled so its not showing generated areas.

image

**Comment by BrainSlayer** [comment]
seems that its time for a whole rewrite of the about page. mist information about the edition is for routers from 2006. most info can be simply removed and replaced with goethe's faust

**Comment by BrainSlayer** [comment]
merging now. review need some time since you reformated everything which is bad for comparing.

**Comment by the-j0k3r** [comment]
> merging now. review need some time since you reformated everything which is bad for comparing.

did you use the whitespace ignore links above on first post?

**Comment by BrainSlayer** [comment]
i used the patch as is. ah and your progress.svg contained windows line breaks. i removed them

**Comment by the-j0k3r** [comment]
> i used the patch as is. ah and your progress.svg contained windows line breaks. i removed them

Thanks, does it work when in use?

may need some margin adjustments in css to display in correct place.

**Comment by BrainSlayer** [comment]
the svg progress bar has no scrolling animation anymore , but just 3 vertical changing bars. not sure if this was your intension

**Comment by BrainSlayer** [comment]
image

**Comment by the-j0k3r** [comment]
> the svg progress bar has no scrolling animation anymore , but just 3 vertical changing bars. not sure if this was your intension

idk what scrolling animation is, if you mean indeterminate always going round and round, then this is the same idea.

before:

image

now:

image

its the same exact idea, something that doesn't have a specific known end.

But yes I see that the top margin needs adjusting and probably another small tweak from the screenshot you show.

**Comment by BrainSlayer** [comment]
> > i used the patch as is. ah and your progress.svg contained windows line breaks. i removed them
> 
> Thanks, does it work when in use?
> 
> may need some margin adjustments in css to display in correct place.

sure it works. after adjustments for handling the error style.

**Comment by the-j0k3r** [comment]
> sure it works. after adjustments for handling the error style.

 I meant the progress svg needs css adjustments where its being called from, ill do those later,

I just have some huge annoyance dd-wrt side, when Im changing styles whatever and click apply the access restrictions I have preset are all mangled https://svn.dd-wrt.com/ticket/7457#comment:14

**Comment by BrainSlayer** [comment]
i just checked it with current builds. cannot find any error

**Comment by BrainSlayer** [comment]
btw the presets arent mangeld. just the selection has a invalid state if the http server is restarted. just switch to 2 and 1 back and all is okay. i fixed that now

**Comment by the-j0k3r** [comment]
> btw the presets arent mangeld. just the selection has a invalid state if the http server is restarted. just switch to 2 and 1 back and all is okay. i fixed that now

Well, thats not the experience, this list blocks some clients from accessing the WAN, and they were fully accessing it, which is risky, because they are very old boxes that have a million security issues.

I dont understand, how clicking apply was also killing the wifi, when I re-did the access list name.

With everyone working from home and via wifi, the Internet is gone again shout. was in  every time. =)

**Comment by BrainSlayer** [comment]
you did not get the point. what you saw was just a gui glitch. access restrictions is not for blocking wan clients. its for blocking services from your lan.

**Comment by BrainSlayer** [comment]
and i mean in your test you set every day and everything to deny. what else did you expect?

**Comment by the-j0k3r** [comment]
> and i mean in your test you set every day and everything to deny. what else did you expect?

only specific lan clients, none affect the wifi, I mean, its worked fine for a long time until 3 builds ago

**Pull request closed without merging**
